language: node_js
node_js:
- 8.9
cache:
  directories:
  - node_modules
script:
- node scripts/env-test
- npm test
notifications:
  slack:
    rooms:
      secure: iYfUvR99LkShUrkyJoqU8apr+bEN6FRGpqLeLxLhvS+9xVT+MWWytHxes6g7HlYiKARjbFWnnQdeVSb2aIr5oiLRc/3lfx30mCED/UZCAi6K1BYWEDOmzRzVwBDvPbG7BZzE9VtvGhRcThIL+8qUXiUW5tqN8mFSho9vA2wsxW/BAquAIdWdk52k9FxsdywrTr0ugc4mWugmH9ExCRz301IHf9a3PSGi2lV8+Zaa2wkiwvcrRzlnpyWucF9wNWzq8gIsiwhPVuKcyk9ngoevYL19HnM3p6UJC9ootu8jKYDHtkLs12XNLZ5fNdoAvAJZpn3K0hkrqZH7280XZNwuYcHmQS52mAmieMUfONzWUu60N0aXCMVzkANcI/UOlhniv3FNQkhBvFA2xG65K4v2Cm0f/HTZUAMfM5ty6T9fhKqvl03IaAn1hzmh9TiTFqnlCX2sFNkMGsswKTqC46sK9ljlGggD1xgkaAY/1oB2c+pK0YYY6uvQJpXlalWO2PJJh65DRYqqfCKfqMZIW+3IS7SU9jDm1vHhsLkdWz2jrJ5KvLAf3USYdtFEnw+pSipjz2Y2C20/7Ky8HJON97BFZxKVu8NhoSUJEE6ngE7/9naPXT+srUsBa1rS+X96eGeJ2sHPU4FYsJUeN0WbxNmPBp/USjW2xRdsi3kWpJ5L0lk=
    template:
    - ":hammer_and_wrench: Build <%{build_url}|#%{build_number}> %{result} in %{duration}\n :octocat: <https://www.github.com/%{repository_slug}/tree/%{branch}|%{repository_slug}@%{branch}> in PR <%{pull_request_url}|#%{pull_request_number}>\n:scroll: (<%{compare_url}|%{commit}>) - _%{commit_message}_\n:godmode: %{author}"
