language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm test
notifications:
  slack:
    secure: tI8CXoHSocfo8tcsH2vNV4IcCAhpvxMF6Hz0rlwwkvHDUoYj9hiJOIaawYmT/Nj2A0Vn2QLUGyMzyGyruUKaau72mSPhCia2XIDAIJ21KoagOqFUrT2Hhv8m9TpmVoJq8dlnDhz7x/E1TtvDwdZq7IAjKyHdZFQ49eohR17Yf64ghaHiB/tJWPv4aBLeI5dtE7suF5/+DwKsMvUMQyY+4tI05qU7fdODk9jhnKWsYpKKYagPYH48VBIs7WNgHTqB/LUo1/jMXX7FKVV67bcKd62nzCFuyruuhcZCyLZlSWctcVZ0ngRzbFGj5SsERRdBpOGXq/YaGeSZG8p5sp+xcEWSGfaOQuFtIUzXLtCUanQoHApUgceVu05qtGOsYTLnnxXD0SNfKyiUuj7IuM7czQ+8Hk4xOXVRo+EPcg05QuLd/425WHI1mcEJaYhaNsqN2TBAdqo/onkKS4UpQxjY2wCVbArmaKinWEQNNHQQiurG7Q/pyAjCqJR/IbXQ5vdTZHi/OHHfMK53EGQDqk8ACIQNtN3205/aF0Rr2fto2b00QxQhEEXyj5/0caOXREBN/+W+df8RGMom+OmE6KwWHXE8J2SxU3s67OKFzOpyt+1R6X8TzrL/Y98payykiwVrRv+2Movz/U72WyTANWwQ97mBzjJjmvMrZeoOpH8cn0U=
env:
  global:
    secure: "ZKXedkqdmz11uhksQDK6JtlYrsFfGR8cl/SF1vmrpcK0jmX41g6tvlxcM0U047I3WqXGy0yFwX0ZTZ4z4mhmXonvh/GNiwtRKxa98KXYppazdnMfjrLLajx19LhAhv/0lS4bwNY6T9d+j3gRs3qfVCSAtl5ln3N/C4lEEKLDX4ElPTWdjmhc0CPzCe8QpUsYZesv3tegrKILxMWPNIdx3khjpbDkW6+UzUt0oVpmwMVGt6W8Mv/YLHYc9+jcqx59K3iZdDJbtMsuSHBsDzU/Zi9J1EKXwJOh1UV5ZkD+HZKKMGZsfoAYK3yqRK6qIxB26ysIjCsOG/Vd5VNQLoBET/JVPwkL9Wom0pZbBtu5S5vG2JTC6vhu2m71qKrJRJgRCOBXxh2K5RFc6YVB1Pb79sDr/NBBjJGofRfsUj/OJc4Fm9+9sedUWIeTw1RMFPxFbpmVek++hFi7CqzpE0D+0khj4f7HAP+PkuHk81iNZsUHJ4nKVNzmcC0xkqm2hMWkbew2mHOjUIrss9QKpfK9TpldUvEbU7McgcrnK/UAEw0bo4XsbqsI+ivRAER4qqL8uFs/UpCoVTB40KG/60lG+pA4zgmvKgLXW91vbbAeLMobzzMzpIRSEI0wOsJIXXt+KMns/VH5ZjHyDKht6N4PIJt7LbcQ/AQlH17GHSz4LoE="
