language: node_js
node_js:
- 8.9
cache:
  directories:
  - node_modules
script:
- node scripts/env-test
- npm test
notifications:
  slack:
    rooms:
      secure: olqOubqk0rvTPexwxV7CU3bf2PfT/JvF1BjunY22+MtV9ss1Tv4Bd+Z1dtP5Jax7tMfvIEt+JDHlk+LpLO+INAAB5p7n85Tu54KiEYH89SqVEsBeMBpEHuYJainXx9LdGQ3QUfweLI1/An3J9eoJZyWkTAdULqBwV93lbOfrIW+U2LD7u7uTHErgyvC2QrLXWZ1QfkWe4GtCNeQTjC3/8KwIFCxEAqDurGUA21EduYctuV3gOHqonvGJzyz69rs2T3j47uZCAWcw1xEmXbZOp5BrU+kyuAuD7+qpbUAv4+j2/EWvXjPLaIcMmlhXpbrsh/ZhDeLMIjwCKKsVWJD4x2yyvu8v1ZBFUrS9087JOo3r+YavBT9oSLJJcg7lMVijDnSkCjoqxGWEX/wmFK+4dzVki4XVDeFb5E7Ba+RtGl8+1kRNDiPXv1bYsJWf2E2Jio9oMxx5iTRaY98ygjarFMOym2IYUClpat7Zxwft6PZIpHHVifTMb6HuUKrIXDA21mYp1vxcf6btJQy2c6jztblYkw3vNZHHJ6GIAAKMRwOXHlVFcM6RVAo19TxBHt+dlBb30rnnWEeCgDWclPa0crwp/li5iEfRfTRTMJjctbVxD/NUa/RSKrg5DVJ5ISt6AhDNVWX/QWWxpV1oOuQz9LJ8Ckk64FW/20RR/HXdwWA=
    template:
    - ":hammer_and_wrench: Build <%{build_url}|#%{build_number}> %{result} in %{duration}\n :octocat: <https://www.github.com/%{repository_slug}/tree/%{branch}|%{repository_slug}@%{branch}> in PR <%{pull_request_url}|#%{pull_request_number}>\n:scroll: (<%{compare_url}|%{commit}>) - _%{commit_message}_\n:godmode: %{author}"
