// flow-typed signature: ee2e433060f026d768f53e990e1cd33f
// flow-typed version: <<STUB>>/react-native-splash-screen_v3.0.6/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-splash-screen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-splash-screen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-splash-screen/index' {
  declare module.exports: $Exports<'react-native-splash-screen'>;
}
declare module 'react-native-splash-screen/index.js' {
  declare module.exports: $Exports<'react-native-splash-screen'>;
}
